name: Rider-Location-Service

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Start Logging
        run: echo Gradle Build Test Start

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build jar
        run: ./gradlew --info bootJar

      - name: Run Unit test
        run: ./gradlew --info rider-location-service:test

      - name: Run integration tests
        run: ./gradlew --info rider-location-service:integrationTest

      - name: Generate Jacoco Test Coverage
        run: ./gradlew --info rider-location-service:generateJacocoTestCoverage

      - name: Comment test coverage on PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        with:
          title: üìù ÌÖåÏä§Ìä∏ Ïª§Î≤ÑÎ¶¨ÏßÄ Î¶¨Ìè¨Ìä∏
          paths: ${{ github.workspace }}/rider-location-service/build/jacoco/index.xml
          token: ${{ secrets.GITHUB_TOKEN }}

      # YML ÌååÏùº ÏÉùÏÑ±
      - name: Make application.properties
        run: |
          cd ./src/main/resources
          touch ./application.yml
          echo "${{ secrets.LOCATION_YML }}" >> ./application.yml
        shell: bash

      - name: ÎèÑÏª§ Ïù¥ÎØ∏ÏßÄ ÎπåÎìú
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rider-location-service:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/rider-location-service:latest

      - name: AWS Î∞∞Ìè¨
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST_LOCATION }}
          username: ubuntu
          key: ${{ secrets.AWS_KEYPAIR_LOCATION }}
          script: |
            sudo docker rm -f $(docker ps -aq)
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/rider-location-service:latest
            sudo docker run -it --rm -e JAVA_OPTS="-Xms1G -Xmx2G" -d --name potato -p 8080:8080 tangpoo/rider-location-service
            sudo docker image prune -f